DROP DATABASE IF EXISTS keanu_db;
CREATE DATABASE keanu_db;

USE keanu_db;

CREATE TABLE films (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) UNIQUE NOT NULL,
    release_year INT UNSIGNED NOT NULL,
    synopsis VARCHAR(1000) UNSIGNED NOT NULL
);